// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	Age    int    `json:"age"`
	Name   string `json:"name"`
	Gender int    `json:"gender"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	User *User  `json:"user"`
}

type User struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Age    int    `json:"age"`
	Gender int    `json:"gender"`
}
